// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Tiếng Việt — bản dịch hoàn chỉnh và trau chuốt theo chuẩn giao diện macOS.
extension Strings {
    static let vi = Strings(
        statusIdleTooltip: "Vorssaint: trạng thái ngủ bình thường",
        statusActiveUntil: "Vorssaint: giữ thức đến",
        statusActiveIndefinite: "Vorssaint: giữ thức vô thời hạn",
        menuEnableAwake: "Bật giữ thức",
        menuDisableAwake: "Tắt giữ thức",
        menuActivateFor: "Kích hoạt trong…",
        menuSettings: "Cài đặt…",
        menuAbout: "Giới thiệu về Vorssaint",
        menuQuit: "Thoát Vorssaint",
        menuHide: "Ẩn Vorssaint",
        menuHideOthers: "Ẩn các mục khác",
        menuShowAll: "Hiện tất cả",
        menuEdit: "Sửa",
        menuUndo: "Hoàn tác",
        menuRedo: "Làm lại",
        menuCut: "Cắt",
        menuCopy: "Sao chép",
        menuPaste: "Dán",
        menuSelectAll: "Chọn tất cả",
        menuWindow: "Cửa sổ",
        menuMinimize: "Thu nhỏ",
        menuZoom: "Thu phóng",
        menuClose: "Đóng",

        minutes15: "15 phút",
        minutes30: "30 phút",
        hour1: "1 giờ",
        hours2: "2 giờ",
        hours4: "4 giờ",
        hours8: "8 giờ",
        indefinitely: "Vô thời hạn",
        indefinite: "Không giới hạn",

        panelSettings: "Cài đặt",
        panelQuit: "Thoát",
        panelHotkeyHint: "Phím tắt chuyển đổi",

        keepAwakeTitle: "Giữ thức",
        keepAwakeEndsIn: "Kết thúc sau",
        keepAwakeUntilDisabled: "Hoạt động cho đến khi bạn tắt",
        keepAwakeNormalRules: "Máy Mac tuân theo quy tắc năng lượng thông thường",
        keepAwakeOptions: "Tùy chọn",
        keepAwakeMouseJiggle: "Di chuyển nhẹ con trỏ",
        keepAwakeMouseJiggleCaption: "Trong phiên, di chuyển nhẹ con trỏ theo khoảng thời gian đã chọn.",
        keepAwakeMouseJiggleInterval: "Khoảng thời gian",
        keepAwakeActiveIconLabel: "Biểu tượng hoạt động",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Cà phê",
        keepAwakeActiveIconEye: "Mắt",
        keepAwakeActiveIconMoon: "Mặt trăng",
        keepAwakeActiveIconLight: "Bóng đèn",
        keepAwakeIconTintLabel: "Màu biểu tượng hoạt động",
        keepAwakeIconTintOrange: "Cam",
        keepAwakeIconTintGreen: "Xanh lục",
        keepAwakeIconTintBlue: "Xanh lam",
        keepAwakeIconTintPurple: "Tím",
        keepAwakeIconTintPink: "Hồng",
        keepAwakeIconTintNone: "Không màu",
        durationLabel: "Thời lượng",
        clamshellTitle: "Tiếp tục chạy khi gập màn hình",
        clamshellOnCaption: "Đã tắt hoàn toàn chế độ ngủ. Chú ý nguồn điện",
        clamshellNeedsSession: "Áp dụng mỗi khi “Giữ thức” đang hoạt động",
        clamshellReady: "Sẵn sàng. Bật/tắt không cần mật khẩu",
        clamshellNeedsPassword: "Sẽ hỏi mật khẩu quản trị viên một lần",

        systemSection: "Hệ thống",
        temperatures: "Nhiệt độ",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Pin",
        usageSection: "Mức sử dụng phần cứng",
        memorySection: "Bộ nhớ",
        memoryPressure: "Áp lực",
        memorySwapUsed: "Swap đã dùng",
        memoryCompressed: "Đã nén",
        memoryCachedFiles: "Tệp trong bộ nhớ đệm",
        pressureNormal: "Bình thường",
        pressureWarning: "Chú ý",
        pressureCritical: "Nghiêm trọng",
        monitorUnavailable: "Cảm biến không khả dụng trên máy Mac này",
        energyAppsTitle: "Ứng dụng tiêu hao nhiều năng lượng",
        energyAppsIdle: "Không có mức sử dụng năng lượng đáng kể",

        notifySessionEndedTitle: "Phiên đã kết thúc",
        notifySessionEndedBody: "Đã hết thời gian. Máy Mac sẽ ngủ bình thường trở lại.",
        notifyBatteryTitle: "Đã tắt Vorssaint",
        notifyBatteryBody: "Pin yếu. Đã khôi phục chế độ ngủ bình thường để bảo vệ pin.",
        adminPromptClamshellOn: "Vorssaint cần mật khẩu của bạn để giữ máy Mac hoạt động khi gập màn hình.",
        adminPromptClamshellOff: "Vorssaint cần mật khẩu của bạn để khôi phục chế độ ngủ bình thường của máy Mac.",
        adminPromptRecover: "Vorssaint đã thoát khi chế độ ngủ của máy Mac bị tắt. Nhập mật khẩu để khôi phục chế độ ngủ bình thường.",
        adminPromptUpdate: "Vorssaint cần mật khẩu của bạn để cài đặt bản cập nhật.",
        adminPromptSudoersInstall: "Vorssaint sẽ tạo quy tắc giới hạn (chỉ pmset disablesleep) để bật tắt chế độ gập màn hình mà không cần hỏi mật khẩu. Đây là lần duy nhất cần mật khẩu.",
        adminPromptSudoersRemove: "Vorssaint sẽ xóa quy tắc gập màn hình không cần mật khẩu.",

        settingsTitle: "Cài đặt Vorssaint",
        tabGeneral: "Cài đặt chung",
        tabEnergy: "Năng lượng",
        tabMouse: "Chuột & Bàn di chuột",
        tabSwitcher: "Bộ chuyển đổi",
        tabAdvanced: "Nâng cao",
        tabAbout: "Giới thiệu",
        tabReleaseNotes: "Có gì mới",
        releaseNotesOnUpdateToggle: "Hiển thị tính năng mới sau khi cập nhật",
        whatsNewDontShowAgain: "Không hiển thị lại",
        previewSizeLabel: "Kích thước xem trước",
        previewSizeNormal: "Bình thường",
        previewSizeLarge: "Lớn",
        previewSizeXLarge: "Rất lớn",
        settingsGroupFeatures: "Tính năng",
        advancedResetSection: "Quyền hạn",
        advancedResetDescription: "Xóa tất cả các quyền bạn đã cấp cho Vorssaint (Trợ năng, Ghi màn hình, Quyền truy cập toàn phần vào đĩa và các quyền khác), mục khởi động cùng hệ thống và quy tắc gập màn hình. Hữu ích để bắt đầu lại hoặc trước khi gỡ cài đặt. Ứng dụng vẫn được cài đặt.",
        advancedClearButton: "Xóa tất cả quyền",
        advancedCleared: "Đã xóa các quyền.",
        advancedClearConfirmTitle: "Xóa tất cả các quyền?",
        advancedClearConfirmBody: "Các tính năng cần quyền sẽ ngừng hoạt động cho đến khi bạn cấp lại. Cài đặt của bạn vẫn được giữ nguyên.",
        advancedUninstallSection: "Gỡ cài đặt",
        advancedUninstallDescription: "Thực hiện tất cả các bước trên, sau đó xóa tùy chọn và chuyển Vorssaint vào Thùng rác, không để lại dữ liệu thừa. Ứng dụng sẽ thoát khi hoàn tất. Bạn có thể cài đặt lại bất cứ lúc nào.",
        advancedUninstallButton: "Gỡ cài đặt hoàn toàn Vorssaint",
        advancedUninstallConfirmTitle: "Gỡ cài đặt Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint sẽ xóa quyền, xóa tùy chọn và chuyển vào Thùng rác rồi thoát. Thao tác này không thể hoàn tác từ ứng dụng, nhưng tệp vẫn ở trong Thùng rác cho đến khi bạn dọn sạch.",

        launchAtLogin: "Khởi động cùng hệ thống",
        languageLabel: "Ngôn ngữ",
        menuBarSection: "Thanh menu",
        showCountdown: "Hiển thị thời gian còn lại cạnh biểu tượng",
        globalHotkeySection: "Phím tắt toàn hệ thống",
        hotkeyToggle: "Bật phím tắt cho “Giữ thức”",
        hotkeyCaption: "Hoạt động trong mọi ứng dụng, không cần thêm quyền.",

        sessionSection: "Phiên hoạt động",
        defaultDurationLabel: "Thời lượng mặc định",
        keepAwakeAutoStart: "Giữ thức khi mở Vorssaint",
        keepAwakeAutoStartCaption: "Bắt đầu phiên với thời lượng mặc định.",
        batteryProtectionSection: "Bảo vệ pin",
        batteryDisableBelow: "Tắt khi pin xuống dưới",
        batteryNever: "Không bao giờ",
        batteryProtectionCaption: "Ngăn phiên hoạt động bị quên làm cạn pin MacBook.",
        clamshellSection: "Gập màn hình",
        configuring: "Đang cấu hình…",
        sudoersFailed: "Không thể bật chế độ gập màn hình. Hãy thử lại.",
        clamshellExplanation: "“Tiếp tục chạy khi gập màn hình” sẽ tắt hoàn toàn chế độ ngủ trong khi “Giữ thức” đang hoạt động và tự động hoàn tác khi phiên kết thúc hoặc ứng dụng thoát. Nên sử dụng khi cắm sạc.",

        scrollSection: "Cuộn",
        invertMouseScroll: "Đảo ngược chiều cuộn chuột",
        invertMouseScrollCaption: "Đảo ngược hướng lăn của con lăn chuột.",
        scrollTrackpadNote: "Bàn di chuột không bị ảnh hưởng: vẫn giữ tính năng cuộn tự nhiên của macOS.",
        scrollActiveNow: "Đang đảo ngược chiều cuộn chuột",
        mouseNavigationActiveNow: "Các nút cạnh đang hoạt động",
        smoothScrollName: "Cuộn mượt mà",
        smoothScrollCaption: "Biến mỗi bước cuộn con lăn thành một chuyển động lướt êm ái. Bàn di chuột không bị ảnh hưởng.",
        smoothScrollStepLabel: "Khoảng cách mỗi bước",
        mouseNavigationSection: "Điều hướng",
        mouseNavigationEnable: "Dùng các nút cạnh để Quay lại và Tiến lên",
        mouseNavigationCaption: "Biến các nút Back và Forward trên chuột thành lệnh điều hướng trong Finder, trình duyệt và các ứng dụng tương thích.",
        middleClickSection: "Nhấp chuột giữa",
        middleClickEnable: "Nhấp bằng ba ngón tay như chuột giữa",
        middleClickEnableCaption: "Nhấn bàn di chuột bằng 3 ngón tay hoạt động như nhấp con lăn: mở liên kết trong tab mới, đóng tab và mọi chức năng khác của nút giữa.",
        middleClickDragConflict: "Tính năng kéo bằng ba ngón tay của macOS đang bật và dùng cùng cử chỉ này. Tắt tính năng đó trong Cài đặt hệ thống > Trợ năng > Điều khiển con trỏ > Tùy chọn bàn di chuột để nhấp chuột giữa hoạt động.",
        middleClickTapPicker: "Chạm nhẹ cũng tính là nhấp",
        middleClickTapOff: "Tắt",
        middleClickTapThreeFingers: "3 ngón tay",
        middleClickTapFourFingers: "4 ngón tay",
        middleClickTapCaption: "Chạm nhẹ với số ngón tay tương ứng mà không cần nhấn cũng kích hoạt nhấp chuột giữa. Vuốt nhẹ không được tính. Nếu cử chỉ chạm ba ngón của macOS được gán cho Tra cứu, hãy tắt để tránh xung đột.",
        quickToolsTab: "Bảng thao tác nhanh",
        quickToolShortcutToggle: "Phím tắt toàn hệ thống",
        ocrName: "Sao chép văn bản từ màn hình",
        ocrCaption: "Chọn một vùng trên màn hình và văn bản nhận diện được sẽ được sao chép, sẵn sàng để dán.",
        ocrCopied: "Đã sao chép văn bản",
        ocrNoText: "Không tìm thấy văn bản",
        colorPickerName: "Bộ chọn màu",
        colorPickerCaption: "Lấy màu của bất kỳ điểm ảnh nào trên màn hình và sao chép theo định dạng ưa thích của bạn.",
        colorPickerFormatLabel: "Định dạng sao chép",
        colorPickerBareHexToggle: "Sao chép không có tiền tố #",
        colorPickerPickNow: "Chọn màu",
        micMuteName: "Tắt tiếng micrô",
        micUnmuteName: "Bật tiếng micrô",
        micMuteCaption: "Ngắt micrô của máy Mac bằng một cú nhấp hoặc phím tắt trên mọi ứng dụng.",
        micMutedHUD: "Đã tắt tiếng micrô",
        micUnmutedHUD: "Đã bật lại micrô",
        micMuteMenuBarToggle: "Hiển thị trên thanh menu khi bị tắt tiếng",
        micMuteMenuBarCaption: "Biểu tượng mic gạch chéo đỏ xuất hiện cạnh biểu tượng ứng dụng trên thanh menu.",
        pastePlainName: "Dán dưới dạng văn bản thuần túy",
        pastePlainCaption: "Dán nội dung bạn đã sao chép mà không có màu sắc, phông chữ hoặc định dạng. Bản gốc vẫn còn trên bảng tạm.",
        launcherName: "Bảng thao tác nhanh",
        launcherCaption: "Một bảng nổi chứa các công cụ ưa thích của bạn, gọi nhanh bằng phím tắt từ bất kỳ đâu.",
        launcherOpenNow: "Mở bảng thao tác nhanh",
        launcherEditHint: "Sử dụng nút tùy chỉnh để chọn, ẩn và kéo sắp xếp các công cụ.",
        launcherEmptyState: "Tất cả công cụ đều bị ẩn. Dùng nút tùy chỉnh để thêm lại.",
        launcherAddSection: "Thêm lại",
        launcherKeysHint: "Phím mũi tên để điều hướng, Enter để mở, 1 đến 9 mở trực tiếp",

        switcherSection: "Trình chuyển ứng dụng",
        switcherEnable: "Sử dụng trình chuyển đổi Vorssaint",
        switcherEnableCaption: "Chuyển đổi giữa các ứng dụng và cửa sổ, bao gồm các cửa sổ bị thu nhỏ và nhiều cửa sổ của cùng một ứng dụng.",
        switcherUsageHint: "Giữ phím tắt để điều hướng; thả ra để kích hoạt cửa sổ. Shift hoặc ← để quay lại; W đóng cửa sổ; Q thoát ứng dụng; Esc để hủy.",
        switcherNoWindows: "Không có cửa sổ nào đang mở",
        switcherIconRowMode: "Hiển thị %@ với biểu tượng lớn",
        switcherIconRowModeCaption: "Hiển thị một biểu tượng cho mỗi ứng dụng với các bản xem trước cửa sổ ở phía trên.",
        switcherSimpleMode: "Trình chuyển đổi ứng dụng đơn giản",
        switcherSimpleModeCaption: "Chỉ hiển thị biểu tượng ứng dụng và tiêu đề cửa sổ, không hiển thị bản xem trước hay chụp màn hình.",
        switcherShortcutHintApps: "Ứng dụng",
        switcherShortcutHintWindows: "Cửa sổ",
        switcherWindowShortcutCaption: "Mở trình chuyển đổi cho các cửa sổ của ứng dụng hiện tại. Khi trình chuyển Ứng dụng đang mở, chuyển giữa các cửa sổ của ứng dụng đã chọn.",
        switcherMergeTabs: "Hiển thị một mục cho mỗi ứng dụng",
        switcherMergeTabsCaption: "Gộp tất cả cửa sổ của một ứng dụng thành một mục trong trình chuyển đổi thay vì mỗi cửa sổ một mục.",
        switcherWindowlessApps: "Ứng dụng không có cửa sổ mở",
        switcherWindowlessAppsCaption: "Chọn ứng dụng đang chạy không có cửa sổ nào sẽ xuất hiện trong trình chuyển đổi.",
        switcherWindowlessAppsOff: "Không hiển thị",
        switcherWindowlessAppsFinder: "Chỉ Finder",
        switcherWindowlessAppsAll: "Tất cả ứng dụng",
        switcherNoOpenWindow: "Không có cửa sổ đang mở",
        switcherOtherDesktop: "Màn hình khác",
        dockPreviewName: "Xem trước trên Dock",
        dockPreviewEnable: "Xem trước cửa sổ từ Dock",
        dockPreviewEnableCaption: "Di chuột qua một ứng dụng đang mở trên Dock để xem các cửa sổ của ứng dụng đó, sau đó nhấp vào cửa sổ bạn muốn.",
        dockPreviewBackgroundOpacity: "Nền bảng điều khiển",
        dockPreviewBackgroundOpacityCaption: "Giảm độ mờ để nhìn rõ hơn các nội dung phía sau bảng điều khiển.",
        dockPreviewOpenDelay: "Độ trễ khi mở",
        dockPreviewOpenDelayCaption: "Thời gian con trỏ dừng trên biểu tượng trước khi bảng xem trước mở ra.",
        dockClickMinimize: "Nhấp vào biểu tượng Dock để thu nhỏ",
        dockClickMinimizeCaption: "Các cửa sổ của ứng dụng hiện tại sẽ thu nhỏ khi bạn nhấp vào biểu tượng Dock của nó. Nhấp lại để mở lại.",
        dockClickCycleWindows: "Nhấp vào biểu tượng Dock để xoay vòng cửa sổ",
        dockClickCycleWindowsCaption: "Nhấp vào biểu tượng Dock của ứng dụng hiện tại để luân chuyển qua các cửa sổ của ứng dụng đó, tương tự như ⌘`.",
        dockPreviewActiveNow: "Đang hoạt động trong Dock",
        dockPreviewDockUnavailable: "Không thể đọc các mục Dock.",
        dockPreviewAutohideBeta: "Beta. Bạn có thể gặp một số lỗi nhỏ.",
        dockPreviewOpenWindow: "Mở cửa sổ",
        dockPreviewCloseWindow: "Đóng cửa sổ",
        dockPreviewMinimizeWindow: "Thu nhỏ cửa sổ",
        dockPreviewRestoreWindow: "Khôi phục cửa sổ",
        dockPreviewPinPanel: "Ghim bản xem trước",
        dockPreviewUnpinPanel: "Bỏ ghim bản xem trước",
        dockPreviewPinned: "Đã ghim",
        dockPreviewClosePanel: "Đóng bản xem trước",
        dockPreviewPreviousWindow: "Cửa sổ trước",
        dockPreviewNextWindow: "Cửa sổ tiếp theo",

        cutPasteName: "Cắt & Dán",
        cutPasteEnable: "Cắt & dán tệp trong Finder",
        cutPasteEnableCaption: "Dùng ⌘X để cắt và ⌘V để di chuyển tệp và thư mục trong Finder.",
        cutPasteShowHUD: "Hiển thị bảng nổi",
        cutPasteShowHUDCaption: "Hiển thị chỉ báo nổi với các tệp đã cắt khi Finder đang hoạt động.",
        cutPasteHowTitle: "Cách sử dụng",
        cutPasteStep1: "Chọn các mục trong Finder và nhấn ⌘X để cắt.",
        cutPasteStep2: "Mở thư mục đích và nhấn ⌘V để di chuyển chúng tới đó.",
        cutPasteTextNote: "Trong các trường văn bản (như khi đổi tên), ⌘X và ⌘V vẫn hoạt động bình thường.",
        cutPasteActiveNow: "Sẵn sàng cắt trong Finder",
        cutPasteAutomationNote: "Lần đầu tiên, macOS sẽ yêu cầu quyền điều khiển Finder.",
        cutReadyTitle: "Đã cắt",
        cutReadyHint: "trong thư mục đích để di chuyển",
        cutCancel: "Hủy cắt",
        cutDoneTitle: "Đã di chuyển!",
        cutMovedSingular: "Đã di chuyển 1 mục",
        cutMovedPluralFormat: "Đã di chuyển %d mục",
        cutSomeFailed: "Không thể di chuyển một số mục",
        cutMovingTitle: "Đang di chuyển…",
        cutMovingCountFormat: "%d / %d",

        autoQuitName: "Thoát khi đóng",
        autoQuitEnable: "Thoát ứng dụng khi đóng cửa sổ cuối cùng",
        autoQuitEnableCaption: "Đóng cửa sổ cuối cùng của ứng dụng cũng sẽ thoát ứng dụng đó.",
        autoQuitActiveNow: "Đang hoạt động",
        autoQuitHowTitle: "Cách hoạt động",
        autoQuitStep1: "Đóng cửa sổ cuối cùng của ứng dụng (⌘W hoặc nút màu đỏ).",
        autoQuitStep2: "Ứng dụng tự động thoát. Hộp thoại “Lưu thay đổi?” vẫn xuất hiện nếu có.",
        autoQuitPredictableNote: "Các ứng dụng chạy nền không có cửa sổ sẽ không bao giờ bị thoát.",
        autoQuitExceptionsTitle: "Ngoại lệ",
        autoQuitExceptionsCaption: "Các ứng dụng trong danh sách này vẫn mở ngay cả khi không có cửa sổ nào.",
        autoQuitExceptionsEmpty: "Không có ngoại lệ",
        autoQuitAddApp: "Thêm ứng dụng…",

        uninstallerName: "Trình gỡ cài đặt",
        uninstallerEnableCaption: "Xóa ứng dụng cùng với bộ nhớ đệm, tệp tùy chọn, nhật ký và dữ liệu rác để lại.",
        uninstallerStep1: "Kéo ứng dụng vào Cài đặt hoặc chọn một ứng dụng từ danh sách.",
        uninstallerStep2: "Xem lại các tệp tìm thấy và dung lượng chúng chiếm dụng.",
        uninstallerStep3: "Chuyển các mục bạn muốn vào Thùng rác. Không có gì bị xóa vĩnh viễn ngay lập tức.",
        uninstallerMenuItem: "Gỡ cài đặt ứng dụng…",
        uninstallerDropTitle: "Kéo ứng dụng vào đây",
        uninstallerDropSubtitle: "hoặc chọn một ứng dụng để quét",
        uninstallerChoose: "Chọn ứng dụng…",
        uninstallerPickerTitle: "Chọn ứng dụng",
        uninstallerPickerSearch: "Tìm kiếm ứng dụng",
        uninstallerPickerEmpty: "Không tìm thấy ứng dụng",
        uninstallerEmptyNote: "Không có gì bị xóa nếu không có sự xác nhận của bạn.",
        uninstallerFDANote: "Cấp Quyền truy cập toàn phần vào đĩa để quét kỹ hơn.",
        uninstallerFDAGrant: "Cấp quyền truy cập…",
        uninstallerFDAHint: "Bật Vorssaint trong danh sách. Nếu không có ở đó, nhấp vào + và chọn Vorssaint từ mục Ứng dụng. Quyền truy cập chỉ có hiệu lực sau khi bạn mở lại ứng dụng.",
        uninstallerFDARelaunch: "Khởi chạy lại ngay",
        uninstallerScanning: "Đang quét tệp…",
        uninstallerRemoving: "Đang chuyển vào Thùng rác…",
        uninstallerFoundTitle: "đã tìm thấy",
        uninstallerSelectedFormat: "Đã chọn %d / %d",
        uninstallerRemove: "Chuyển vào Thùng rác",
        uninstallerCancel: "Hủy",
        uninstallerDoneTitle: "Hoàn tất!",
        uninstallerFreedFormat: "Đã thu hồi %@",
        uninstallerSomeFailed: "Không thể chuyển một số mục vào Thùng rác.",
        uninstallerFailedNeedsFDA: "Dữ liệu ứng dụng Sandbox chỉ có thể di chuyển với Quyền truy cập toàn phần vào đĩa. Mật khẩu quản trị viên không thể thay thế quyền này.",
        uninstallerFailedMoreFormat: "và thêm %d mục nữa",
        uninstallerAnother: "Gỡ cài đặt ứng dụng khác",
        uninstallerCatApp: "Ứng dụng",
        uninstallerCatSupport: "Dữ liệu hỗ trợ",
        uninstallerCatCaches: "Bộ nhớ đệm",
        uninstallerCatPreferences: "Tùy chọn",
        uninstallerCatContainers: "Containers",
        uninstallerCatLogs: "Nhật ký",
        uninstallerCatState: "Trạng thái đã lưu",
        uninstallerCatOther: "Khác",

        urlCleanerName: "Dọn dẹp URL",
        urlCleanerEnable: "Dọn dẹp URL khi bạn sao chép",
        urlCleanerEnableCaption: "Xóa các tham số theo dõi khỏi liên kết ngay khi nó được đưa vào bảng tạm.",
        urlCleanerActiveNow: "Đang hoạt động",
        urlCleanerManualTitle: "Dọn dẹp ngay",
        urlCleanerInputPlaceholder: "Dán một URL",
        urlCleanerOutputPlaceholder: "URL đã dọn dẹp xuất hiện ở đây",
        urlCleanerCleanButton: "Dọn dẹp",
        urlCleanerPasteButton: "Dán",
        urlCleanerCopyButton: "Sao chép",
        urlCleanerClearButton: "Xóa trường",
        urlCleanerNoURL: "Hãy dán một URL hợp lệ.",
        urlCleanerNoChange: "Không có gì cần dọn dẹp.",
        urlCleanerCleaned: "Đã dọn dẹp URL.",
        urlCleanerCopied: "Đã sao chép.",
        urlCleanerLocalNote: "Cục bộ. Không dùng mạng.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Tìm kiếm, cài đặt và gỡ bỏ formulae và casks.",
        homebrewMissingTitle: "Không tìm thấy Homebrew",
        homebrewMissingBody: "Vorssaint có thể mở Terminal với trình cài đặt chính thức của Homebrew. Terminal sẽ hiển thị các bước và hỏi mật khẩu nếu cần.",
        homebrewInstallHomebrew: "Cài đặt Homebrew",
        homebrewInstallHomebrewCaption: "Khi Terminal hoàn tất, hãy quay lại đây và nhấp vào Làm mới.",
        homebrewInstallHomebrewOpened: "Đã mở trình cài đặt trong Terminal.",
        homebrewShellSetupTitle: "Hoàn tất thiết lập Terminal",
        homebrewShellSetupBody: "Homebrew đã được cài đặt nhưng Terminal có thể chưa tìm thấy lệnh brew. Vorssaint có thể mở Terminal với lệnh thiết lập.",
        homebrewShellSetupButton: "Thiết lập Terminal",
        homebrewShellSetupOpened: "Lệnh đã mở trong Terminal. Sau đó quay lại đây và nhấp vào Làm mới.",
        homebrewRefresh: "Làm mới",
        homebrewCheckPackages: "Kiểm tra gói",
        homebrewTrustTitle: "Tap chưa được tin cậy",
        homebrewTrustCaption: "Homebrew yêu cầu bạn xác nhận trước khi dùng các tap bên thứ ba. Hãy tin cậy %@ để tiếp tục.",
        homebrewTrustButton: "Tin cậy và tiếp tục",
        homebrewSearchPlaceholder: "Tìm kiếm gói",
        homebrewKeyboardHint: "Dấu cách hoặc Return sẽ đóng bảng macOS. Hãy dùng nút tìm kiếm.",
        homebrewSearchButton: "Tìm kiếm",
        homebrewSearchResults: "Kết quả",
        homebrewInstalled: "Đã cài đặt",
        homebrewAll: "Tất cả",
        homebrewFormulas: "Formulae",
        homebrewCasks: "Casks",
        homebrewNoPackages: "Không tìm thấy gói nào",
        homebrewNoSelection: "Chọn một gói đã cài đặt hoặc tìm kiếm gói mới.",
        homebrewDetailsTitle: "Chi tiết gói",
        homebrewInstall: "Cài đặt",
        homebrewUninstall: "Gỡ cài đặt",
        homebrewUpgrade: "Cập nhật",
        homebrewUpgradeAll: "Cập nhật tất cả",
        homebrewUpdateHomebrew: "Cập nhật Homebrew",
        homebrewAllPackages: "gói",
        homebrewOpenTerminal: "Mở Terminal",
        homebrewCancelOperation: "Hủy",
        homebrewClearLog: "Xóa nhật ký",
        homebrewLogTitle: "Nhật ký",
        homebrewVersion: "Phiên bản",
        homebrewDescription: "Loại",
        homebrewHomepage: "Mở trang web",
        homebrewPopularity: "Mức độ phổ biến",
        homebrewPopularityFormat: "%@ lượt cài đặt trong %@ ngày",
        homebrewInstalledBadge: "Đã cài đặt",
        homebrewNotInstalledBadge: "Chưa cài đặt",
        homebrewUpdates: "Bản cập nhật",
        homebrewUpdateAvailableBadge: "Có bản cập nhật",
        homebrewLatestVersion: "Mới nhất",
        homebrewConfirmInstallTitle: "Cài đặt bằng Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew sẽ tải về và cài đặt %@. Các phần phụ thuộc cũng có thể được cài đặt.",
        homebrewConfirmUninstallTitle: "Gỡ cài đặt bằng Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew sẽ gỡ cài đặt %@. Các tệp cấu hình có thể vẫn còn trên hệ thống.",
        homebrewConfirmUpgradeTitle: "Cập nhật bằng Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew sẽ tải về và áp dụng phiên bản mới nhất của %@. Các phần phụ thuộc cũng có thể được cập nhật.",
        homebrewConfirmUpgradeAllTitle: "Cập nhật tất cả bằng Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew sẽ tải về và áp dụng phiên bản mới nhất cho các gói có bản cập nhật. Các phần phụ thuộc cũng có thể được cập nhật.",
        homebrewConfirmUpdateHomebrewTitle: "Cập nhật Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew sẽ lấy thông tin mới nhất và tải lại các gói của bạn.",
        homebrewTerminalFallback: "Thao tác này cần Terminal để hỏi mật khẩu quản trị viên. Vorssaint không thu thập mật khẩu.",
        homebrewLoading: "Đang tải…",
        homebrewSearchEmpty: "Không có kết quả",
        homebrewOperationInstallFormat: "Đang cài đặt %@",
        homebrewOperationUninstallFormat: "Đang gỡ cài đặt %@",
        homebrewOperationUpgradeFormat: "Đang cập nhật %@",
        homebrewOperationUpgradeAll: "Đang cập nhật các gói",
        homebrewOperationUpdateHomebrew: "Đang cập nhật Homebrew",
        homebrewOperationInstalledFormat: "Đã cài đặt %@.",
        homebrewOperationUninstalledFormat: "Đã gỡ cài đặt %@.",
        homebrewOperationUpgradedFormat: "Đã cập nhật %@.",
        homebrewOperationUpgradedAll: "Đã cập nhật các gói.",
        homebrewOperationUpdatedHomebrew: "Đã cập nhật Homebrew.",
        homebrewOperationFailedFormat: "Không thể hoàn tất %@.",
        homebrewOperationCancelled: "Đã hủy thao tác.",
        homebrewOperationPreparing: "Đang chuẩn bị...",
        homebrewOperationDownloading: "Đang tải về tệp...",
        homebrewOperationInstalling: "Đang cài đặt tệp...",
        homebrewOperationUninstalling: "Đang xóa tệp...",
        homebrewOperationUpgrading: "Đang cập nhật tệp...",
        homebrewOperationFinalizing: "Đang hoàn tất...",
        homebrewOperationRefreshing: "Đang làm mới danh sách...",
        homebrewOperationTerminal: "Tiếp tục trong Terminal.",
        homebrewOperationElapsedFormat: "Đã qua %@",
        homebrewOperationShowDetails: "Hiện chi tiết",
        homebrewOperationHideDetails: "Ẩn chi tiết",
        homebrewOperationTechnicalLog: "Chi tiết kỹ thuật",
        homebrewOperationProgressUnknown: "Homebrew chưa báo cáo tỷ lệ phần trăm.",

        mediaName: "Phương tiện",
        mediaEnableCaption: "Nén video, chuyển đổi và xử lý hình ảnh, tạo ảnh GIF và trích xuất văn bản cục bộ.",
        mediaLocalNote: "Cục bộ. Không dùng mạng.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Hình ảnh",
        mediaToolText: "Văn bản",
        mediaSelectFile: "Chọn tệp",
        mediaDropHint: "Thả tệp vào đây hoặc nhấp để chọn một tệp.",
        mediaOutput: "Đầu ra",
        mediaOutputAutomatic: "Tự động",
        mediaChooseOutput: "Đích đến",
        mediaStartVideo: "Nén video",
        mediaStartGIF: "Tạo GIF",
        mediaStartImage: "Xử lý hình ảnh",
        mediaStartConvertPDF: "Chuyển sang PDF",
        mediaStartText: "Trích xuất văn bản",
        mediaCancel: "Hủy",
        mediaStartTime: "Bắt đầu",
        mediaEndTime: "Kết thúc",
        mediaQuality: "Mức độ nén",
        mediaCompressionLow: "Thấp",
        mediaCompressionMedium: "Trung bình",
        mediaCompressionHigh: "Cao",
        mediaMaxSize: "Kích thước",
        mediaSizingResolution: "Độ phân giải",
        mediaSizingFileSize: "Kích thước tệp",
        mediaTargetSize: "Kích thước mục tiêu",
        mediaTargetSizeHint: "Độ phân giải tự điều chỉnh để không vượt quá giới hạn.",
        mediaErrorTargetTooSmall: "Kích thước mục tiêu quá nhỏ cho đoạn video này. Hãy cắt bớt hoặc tăng giới hạn.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Chiều rộng",
        mediaFPS: "FPS",
        mediaKeepAudio: "Giữ âm thanh",
        mediaCodec: "Bộ giải mã",
        mediaFormat: "Định dạng",
        mediaStripMetadata: "Xóa siêu dữ liệu",
        mediaLoopGIF: "Lặp lại GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Chính xác",
        mediaOCRFast: "Nhanh",
        mediaLanguageCorrection: "Sửa lỗi ngôn ngữ",
        mediaTextOutputNote: "Văn bản trích xuất có thể sao chép và lưu dưới dạng TXT.",
        mediaRunning: "Đang xử lý",
        mediaCompleted: "Hoàn tất",
        mediaCancelled: "Đã hủy.",
        mediaOpenInFinder: "Hiển thị",
        mediaCopyText: "Sao chép văn bản",
        mediaRunAgain: "Chạy lại",
        mediaEmptyText: "Không tìm thấy văn bản.",
        mediaResultSavedFormat: "Đã lưu dưới dạng %@",
        mediaResultSizeFormat: "%@ thành %@",
        mediaResultGrewCaption: "Tệp sau khi chuyển đổi có dung lượng lớn hơn tệp gốc.",
        mediaErrorNoFile: "Hãy chọn một tệp trước.",
        mediaErrorNoVideo: "Tệp này không có luồng video.",
        mediaErrorSameOutput: "Chọn đích đến khác với tệp gốc.",
        mediaErrorUnsupported: "Định dạng không được macOS hỗ trợ.",

        shelfName: "Kệ tạm",
        shelfEnable: "Khu vực tạm thời để kéo thả tệp",
        shelfEnableCaption: "Một vị trí nổi để tập hợp tệp, hình ảnh và văn bản, rồi kéo chúng tới bất cứ đâu sau đó.",
        shelfHowTitle: "Cách sử dụng",
        shelfStep1: "Mở bằng phím tắt, hoặc lắc chuột trong khi kéo thả.",
        shelfStep2: "Thả tệp, hình ảnh, liên kết hoặc văn bản vào đó để giữ.",
        shelfStep3: "Kéo từng mục ra bất kỳ ứng dụng nào khi bạn cần.",
        shelfShakeToggle: "Mở bằng cách lắc chuột khi đang kéo",
        shelfShakeCaption: "Lắc nhanh con trỏ trong khi đang giữ một mục để mở kệ ngay gần con trỏ.",
        shelfDropZoneToggle: "Giữ các tệp được kéo trên thanh menu",
        shelfDropZoneCaption: "Khi bạn kéo một tệp, kệ sẽ xuất hiện bên dưới biểu tượng thanh menu. Bất cứ thứ gì bạn thả sẽ được giữ ngay tại đó trong một nút có thể thu gọn và tự biến mất khi kệ trống.",
        shelfDropZoneLabel: "Thả vào đây",
        shelfCollapse: "Thu gọn",
        shelfBehaviorTitle: "Sau khi sử dụng",
        shelfCloseAfterDrop: "Đóng sau khi thả vào ứng dụng khác",
        shelfCloseAfterDropCaption: "Đóng kệ khi ứng dụng đích chấp nhận các mục. Nút ghim trên bảng sẽ giữ kệ luôn mở.",
        shelfRemoveAfterDrop: "Xóa các mục sau khi thả",
        shelfRemoveAfterDropCaption: "Các mục được ứng dụng khác chấp nhận sẽ rời khỏi kệ. Tắt mục này để giữ lại một bản sao.",
        shelfExclusionsTitle: "Ngoại lệ tự động",
        shelfExclusionsEmpty: "Chưa thêm ứng dụng nào.",
        shelfExclusionsCaption: "Lắc chuột và vùng thả thanh menu sẽ tắt đối với các thao tác kéo bắt đầu từ các ứng dụng này. Phím tắt và Mở ngay vẫn hoạt động.",
        shelfPin: "Giữ luôn mở",
        shelfUnpin: "Cho phép đóng sau khi dùng",
        extraBrightnessName: "Độ sáng mở rộng",
        extraBrightnessCaption: "Sử dụng khoảng sáng HDR của màn hình để vượt qua độ sáng tối đa. Tiêu tốn nhiều pin hơn và máy Mac có thể ấm lên.",
        extraBrightnessLevelLabel: "Cường độ",
        extraBrightnessUnsupported: "Chỉ khả dụng trên màn hình XDR, chẳng hạn như trên MacBook Pro 14 và 16 inch.",
        shelfHotkeyLabel: "Phím tắt",
        shelfOpenNow: "Mở ngay",
        shelfNoPermission: "Không yêu cầu quyền.",
        shelfMenuItem: "Mở kệ tạm",
        shelfTitle: "Kệ tạm",
        shelfEmpty: "Kéo các mục vào đây",
        shelfClearAll: "Xóa tất cả",
        shelfRemoveSelected: "Xóa mục đã chọn",
        shelfSelectedFormat: "Đã chọn %d mục",
        shelfHint: "Nhấp để chọn. Kéo ra ngoài để sử dụng hoặc nhấp chuột phải để có thêm tác vụ.",
        shelfItemImage: "Hình ảnh",
        shelfTooltipItemsFormat: "%d mục",
        shelfTooltipImageSingular: "%d hình ảnh",
        shelfTooltipImagePlural: "%d hình ảnh",
        shelfTooltipFileSingular: "%d tệp",
        shelfTooltipFilePlural: "%d tệp",
        shelfTooltipNoteSingular: "%d ghi chú",
        shelfTooltipNotePlural: "%d ghi chú",
        shelfTooltipLinkSingular: "%d liên kết",
        shelfTooltipLinkPlural: "%d liên kết",
        shelfActionOpen: "Mở",
        shelfActionOpenWith: "Mở bằng",
        shelfActionAirDrop: "Chia sẻ qua AirDrop",

        breakdownMeasuring: "Đang đo…",

        mixerSection: "Bộ trộn âm lượng",
        mixerEmpty: "Các ứng dụng phát âm thanh sẽ xuất hiện ở đây",
        mixerUnavailable: "Khả dụng trên macOS 14.4 trở lên",
        mixerPermissionBody: "Để điều chỉnh âm lượng từng ứng dụng, hãy cấp quyền “Ghi âm thanh hệ thống & màn hình” trong Cài đặt hệ thống. Âm thanh không bao giờ bị ghi lại.",
        mixerResetTooltip: "Đặt lại về 100%",
        mixerOutputDefault: "Mặc định",
        mixerOutputCurrent: "hiện tại",
        mixerOutputUnavailable: "Đầu ra không khả dụng",
        mixerOutputFallback: "Dùng mặc định cho đến khi thiết bị này kết nối lại.",
        mixerBypassedCaption: "Ứng dụng này tự quản lý âm thanh của chính nó.",
        mixerOutputTooltip: "Chọn đầu ra",
        mixerSystemOutputTitle: "Đầu ra",
        mixerSystemOutputNoDevices: "Không tìm thấy thiết bị đầu ra",
        mixerSystemOutputTooltip: "Chọn đầu ra hệ thống",
        mixerSystemOutputErrorFormat: "Không thể chuyển đổi: %@",
        mixerLowerOnHeadphonesDisconnect: "Giảm âm lượng khi ngắt kết nối tai nghe",
        mixerLowerOnHeadphonesDisconnectCaption: "Điều chỉnh âm lượng khi tai nghe có dây hoặc Bluetooth bị ngắt kết nối.",
        mixerHeadphonesDisconnectVolume: "Âm lượng sau khi ngắt kết nối",
        preciseVolumeRollerEnable: "Dùng các bước âm lượng nhỏ hơn",
        preciseVolumeRollerCaption: "Biến con lăn âm lượng và các phím thành các bước âm lượng hệ thống nhỏ hơn.",
        preciseVolumeRollerTapFailed: "Không thể theo dõi phím âm lượng.",
        soundOutputSwitcherTitle: "Chuyển đổi đầu ra",
        soundOutputSwitcherEnable: "Chuyển đổi đầu ra bằng phím tắt",
        soundOutputSwitcherCaption: "Chọn các đầu ra và dùng phím tắt để chuyển sang đầu ra khả dụng tiếp theo.",
        soundOutputSwitcherDevices: "Các đầu ra trong vòng lặp",
        soundOutputSwitcherNoAvailableSelection: "Chọn ít nhất một đầu ra khả dụng.",
        mixerInputTitle: "Micrô",
        mixerInputNoDevices: "Không tìm thấy micrô",
        mixerInputUnavailable: "Micrô không khả dụng",
        mixerInputFallback: "Dùng mặc định cho đến khi micrô này kết nối lại.",
        mixerInputTooltip: "Chọn micrô",
        mixerInputErrorFormat: "Không thể chuyển đổi: %@",
        mixerVisibleApps: "Ứng dụng trong danh sách",
        mixerAllShown: "Tất cả",
        mixerHiddenCountLabel: "Đã ẩn",
        mixerHideFromList: "Ẩn khỏi danh sách",

        updatesSection: "Cập nhật",
        autoCheckToggle: "Tự động kiểm tra bản cập nhật",
        includeBetaUpdatesToggle: "Nhận các bản cập nhật Beta",
        includeBetaUpdatesCaption: "Các phiên bản Beta bao gồm các tính năng đang phát triển và có thể chứa lỗi hoặc hành vi chưa hoàn thiện.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Kiểm tra ngay",
        updateChecking: "Đang kiểm tra…",
        updateUpToDate: "Bạn đang ở phiên bản mới nhất.",
        updateAvailablePrefix: "Có bản cập nhật mới:",
        updateInstallButton: "Tải về và cài đặt",
        updateDownloading: "Đang tải về bản cập nhật…",
        updateInstalling: "Đang cài đặt và khởi động lại…",
        updateFailedPrefix: "Không thể kiểm tra:",
        updateLastChecked: "Kiểm tra lần cuối:",
        updateNotifyTitle: "Cập nhật Vorssaint",
        updateInstallFailedBody: "Bản cập nhật đã được tải về nhưng không thể áp dụng. Tải về phiên bản mới nhất từ trang phát hành GitHub và kéo ứng dụng đè lên phiên bản hiện tại.",
        updateNeedsApplicationsTitle: "Di chuyển Vorssaint vào Ứng dụng",
        updateNeedsApplicationsBody: "Ứng dụng đang chạy từ một vị trí không thể cập nhật, chẳng hạn như ảnh đĩa hoặc vị trí hệ thống tạm thời. Kéo Vorssaint vào thư mục Ứng dụng, mở từ đó và thử lại.",
        menuCheckUpdates: "Kiểm tra bản cập nhật…",

        permissionRequired: "Yêu cầu quyền",
        permissionAccessibility: "Trợ năng",
        permissionScreenRecording: "Ghi màn hình",
        permissionGranted: "Đã cấp",
        permissionMissing: "Chưa cấp",
        permissionOpenSettings: "Mở Cài đặt hệ thống…",
        permissionRequest: "Cấp quyền truy cập",
        permissionRestartNote: "macOS có thể yêu cầu mở lại ứng dụng sau khi cấp quyền.",

        aboutDescription: "Trung tâm tiện ích cho máy Mac của bạn.\nNăng lượng, giám sát hệ thống, cuộn chuột và chuyển đổi cửa sổ, ngay trên thanh menu.",
        versionPrefix: "Phiên bản",
        reviewIntro: "Xem lại phần giới thiệu",
        reviewHighlights: "Xem lại điểm nổi bật",
        viewOnGitHub: "Xem trên GitHub",

        obContinue: "Tiếp tục",
        obBack: "Quay lại",
        obSkipStep: "Bỏ qua bước này",
        obStart: "Mở Vorssaint",
        obStepWelcomeTitle: "Chào mừng bạn đến với Vorssaint",
        obStepWelcomeBody: "Tiện ích thanh menu tinh tế giúp trải nghiệm macOS hàng ngày của bạn tiện lợi hơn.",
        obWelcomeBullet1Title: "Kiểm soát năng lượng",
        obWelcomeBullet1Body: "Giữ máy Mac luôn thức bao lâu tùy thích, ngay cả khi gập màn hình.",
        obWelcomeBullet2Title: "Theo dõi hệ thống trực quan",
        obWelcomeBullet2Body: "Nhiệt độ CPU, GPU, pin, mức sử dụng phần cứng và áp lực bộ nhớ theo thời gian thực.",
        obWelcomeBullet3Title: "Chuột và cửa sổ theo cách của bạn",
        obWelcomeBullet3Body: "Đảo chiều cuộn chuột và trình chuyển cửa sổ kèm hình thu nhỏ.",
        obLanguageLabel: "Ngôn ngữ",
        obStepAccessibilityTitle: "Trợ năng",
        obStepAccessibilityBody: "Cần thiết để đảo chiều cuộn chuột và để trình chuyển cửa sổ phản hồi bàn phím.",
        obAccessibilityWhy: "Ứng dụng chỉ theo dõi con lăn chuột và phím tắt chuyển đổi. Không có gì bị ghi lại hoặc gửi đi đâu.",
        obStepRecordingTitle: "Ghi màn hình",
        obStepRecordingBody: "Cho phép trình chuyển đổi hiển thị hình thu nhỏ cửa sổ thực tế thay vì chỉ có biểu tượng.",
        obRecordingWhy: "Hình thu nhỏ được tạo tức thì, lưu trong bộ nhớ và không bao giờ rời khỏi máy Mac. Nếu không có quyền này, trình chuyển đổi vẫn hoạt động với biểu tượng.",
        obStepMonitorTitle: "Giám sát hệ thống",
        obStepMonitorBody: "Bảng điều khiển hiển thị nhiệt độ CPU, GPU, pin, mức sử dụng phần cứng và áp lực bộ nhớ.",
        obMonitorNoPermission: "Không cần cấp quyền. Cảm biến được đọc trực tiếp từ hệ thống.",
        obStepOptionalTitle: "Tính năng tùy chọn",
        obStepOptionalBody: "Bật những gì bạn muốn dùng bây giờ. Mọi thứ đều có thể thay đổi sau trong Cài đặt.",
        obStepStatusTitle: "Kiểm tra",
        obStepStatusBody: "Đảm bảo mọi thứ đã sẵn sàng cho các tính năng bạn muốn.",
        obStatusRecheck: "Kiểm tra lại",
        obStepDoneTitle: "Đã sẵn sàng!",
        obStepDoneBody: "Vorssaint đã bắt đầu đồng hành cùng máy Mac của bạn.",
        obDoneHint: "Tìm biểu tượng lỗ đen trên thanh menu, ở góc trên cùng bên phải màn hình.",
        obWhatsNewTitle: "Có gì mới trong phiên bản này",
        obWhatsNewFallback: "Bản cập nhật này bao gồm các bản sửa lỗi và cải tiến mới nhất.",
        obLanguageUpdateTitle: "Nay đã hỗ trợ ngôn ngữ của bạn",
        obLanguageUpdateBody: "Vorssaint hiện hỗ trợ nhiều ngôn ngữ. Chọn ngôn ngữ bạn muốn sử dụng; bạn có thể đổi bất kỳ lúc nào trong Cài đặt.",
        obPurposeTitle: "Điều gì đưa bạn đến đây?",
        obPurposeBody: "Chọn cấu hình có sẵn hoặc chọn chính xác những gì bạn muốn sử dụng.",
        obPurposeSkip: "Bạn có thể thêm hoặc bớt các tính năng sau trong Cài đặt.",

        tabMonitor: "Giám sát",
        monitorMenuBarSection: "Trên thanh menu",
        monitorMenuBarCaption: "Chọn những gì xuất hiện cạnh biểu tượng trên thanh menu.",
        monitorCombineTemperatures: "Kết hợp mức sử dụng và nhiệt độ",
        monitorCombineTemperaturesCaption: "Khi mức sử dụng và nhiệt độ của cùng một thành phần được bật, hiển thị chúng trong một khối.",
        monitorSeparateMenuBarMetrics: "Tách các chỉ số thành từng mục riêng",
        monitorSeparateMenuBarMetricsCaption: "Tách các khối hoạt động trên thanh menu và giữ mức sử dụng và nhiệt độ cùng nhau khi bật kết hợp.",
        monitorNetworkUploadFirst: "Tải lên phía trên tải về",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Bộ nhớ",
        monitorShowNetwork: "Mạng",
        monitorShowPowerLabel: "Nguồn điện",
        monitorIntervalLabel: "Cập nhật mỗi",
        monitorInterval1: "1 giây",
        monitorInterval2: "2 giây",
        monitorInterval5: "5 giây",
        monitorPanelSection: "Trong bảng điều khiển",
        panelNavigationMode: "Điều hướng bảng theo phần",
        panelNavigationCaption: "Hiển thị từng phần một. Chọn Danh sách để xem tất cả trong một luồng cuộn liên tục.",
        panelFooterSections: "Phần",
        panelFooterList: "Danh sách",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Bạn có thể gặp một số lỗi nhỏ.",

        networkSection: "Mạng",
        networkDownload: "Tải về",
        networkUpload: "Tải lên",
        networkThisSession: "Phiên này",
        networkMeasuring: "Đang đo…",
        networkApps: "Ứng dụng dùng mạng",
        networkAppsIdle: "Không có ứng dụng nào dùng mạng lúc này",

        diskSection: "Ổ đĩa",
        diskUsed: "đã dùng",
        diskFree: "trống",
        diskInternal: "Nội bộ",
        diskExternal: "Bên ngoài",
        diskSelect: "Chọn ổ đĩa",
        diskRead: "Đọc",
        diskWrite: "Ghi",
        diskSMARTStatus: "Trạng thái",
        diskSMARTUnavailable: "SMART không khả dụng cho ổ đĩa này",
        diskTotalRead: "Tổng đã đọc",
        diskTotalWritten: "Tổng đã ghi",
        diskTemperature: "Nhiệt độ",
        diskHealth: "Sức khỏe",
        diskPowerCycles: "Chu kỳ bật",
        diskPowerOnHours: "Số giờ hoạt động",
        diskUnsafeShutdowns: "Tắt máy không an toàn",
        diskMediaErrors: "Lỗi phương tiện",
        diskEject: "Ngắt kết nối",
        diskEjectAll: "Ngắt kết nối tất cả",
        diskEjecting: "Đang ngắt kết nối…",
        diskReadyToRemove: "Sẵn sàng tháo ra",
        diskEjectFailed: "Không thể ngắt kết nối",
        diskProtectionCaption: "Hãy ngắt kết nối trước khi rút cáp.",
        diskNoExternal: "Không có ổ đĩa ngoài nào sẵn sàng để ngắt kết nối.",
        diskOpenInFinder: "Mở",
        diskStorageSettings: "Dung lượng lưu trữ",
        diskNoDisks: "Không tìm thấy ổ đĩa nào được gắn.",

        powerSection: "Nguồn điện",
        powerSystem: "Hệ thống",
        powerAdapter: "Bộ sạc",
        powerBattery: "Pin",
        powerCharging: "Đang sạc",
        powerOnBattery: "Dùng pin",
        powerPluggedIn: "Đã cắm sạc",
        powerUnavailable: "Chỉ số nguồn điện không khả dụng trên máy Mac này",
        powerAdapterMaxFormat: "Tối đa %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Nhiệt độ CPU",
        monitorShowGPUTemperature: "Nhiệt độ GPU",
        monitorShowBatteryTemperature: "Nhiệt độ pin",
        monitorShowPeripheralBattery: "Pin thiết bị ngoại vi",
        peripheralBatteryNoDevices: "Không tìm thấy thiết bị",
        monitorGraphsSection: "Biểu đồ",
        monitorGraphsCaption: "Chọn chỉ số nào sẽ hiển thị biểu đồ theo thời gian.",

        updateBannerTitle: "Có bản cập nhật mới",
        updateBannerAction: "Cập nhật",
        obStepMenuBarTitle: "Chỉ số trên thanh menu",
        obStepMenuBarBody: "Chọn những gì sẽ hiển thị cạnh biểu tượng. Bản xem trước ở trên cập nhật trực tiếp.",
        obStepMenuBarNote: "Mới: Khối mạng, nguồn điện và biểu đồ trong bảng điều khiển. Tinh chỉnh lại sau trong Cài đặt › Giám sát.",
        monitorMenuBarPresetLabel: "Kiểu",
        menuBarPresetReadable: "Dễ đọc",
        menuBarPresetDense: "Dày đặc",
        menuBarSpacingLabel: "Khoảng cách thanh menu",
        menuBarSpacingStandard: "Tiêu chuẩn",
        menuBarSpacingCompact: "Gọn gàng",
        menuBarHideIconToggle: "Ẩn biểu tượng ứng dụng khi hiển thị chỉ số",
        menuBarHideIconCaption: "Biểu tượng tự xuất hiện lại khi các chỉ số rời khỏi thanh menu hoặc khi có tín hiệu cần báo (bản cập nhật sẵn sàng hoặc micrô bị tắt tiếng).",
        monitorLabelStyleLabel: "Nhãn",
        menuBarLabelStyleCompact: "Gọn",
        menuBarLabelStyleClassic: "Cổ điển",
        monitorMemoryStyleLabel: "Hiển thị bộ nhớ dạng",
        monitorMemoryPressureDot: "Chấm áp lực",
        memoryStyleDot: "Chấm",
        memoryStylePercent: "%",
        memoryStyleBoth: "Cả hai",
        systemUptime: "Thời gian hoạt động",
        batteryCharge: "Mức sạc",
        powerHealth: "Tình trạng pin",
        powerCycles: "Số chu kỳ",
        speedTestRun: "Đo tốc độ",
        speedTestAgain: "Đo lại",
        speedTestLatency: "Độ trễ",
        speedTestTesting: "Đang đo…",
        speedTestFailed: "Đo tốc độ thất bại",

        monitorShowInPanel: "Hiện trong bảng điều khiển",
        disclosureExpanded: "Đã mở rộng",
        disclosureCollapsed: "Đã thu gọn",
        panelHideItem: "Ẩn khỏi bảng điều khiển",
        panelShowItem: "Hiện trong bảng điều khiển",
        panelHiddenItem: "Đã ẩn",
        monitorItemUptime: "Thời gian chạy",
        monitorItemNetSpeed: "Tốc độ trực tiếp",
        monitorItemNetTotals: "Tổng phiên",
        monitorItemNetTest: "Đo tốc độ",
        monitorItemDiskUsage: "Dung lượng ổ đĩa",
        monitorItemDiskActivity: "Hoạt động trực tiếp",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Bảo vệ ổ đĩa ngoài",
        monitorItemDiskTools: "Công cụ",
        monitorPanelConfigHint: "Mở một khối để chọn nội dung hiển thị.",
        monitorOrderSection: "Thứ tự các phần",
        monitorOrderHint: "Kéo để sắp xếp lại các phần của bảng và dùng biểu tượng mắt để ẩn hoặc hiện từng phần.",
        obStepPanelTitle: "Có gì trong bảng điều khiển",
        obStepPanelBody: "Mở từng khối và chọn chính xác những gì sẽ hiển thị khi bạn nhấp vào biểu tượng.",
        obStepPanelNavigationTitle: "Bảng điều khiển theo phần",
        obStepPanelNavigationBody: "Bảng điều khiển hiện có thể hiển thị từng phần một. Bạn có thể chuyển đổi giữa Các phần và Danh sách trong Cài đặt.",

        cleaningMenuItem: "Chế độ vệ sinh",
        utilitiesSection: "Tiện ích",
        quickControlsSection: "Điều khiển",
        panelCategoryWindows: "Cửa sổ",
        panelCategoryInput: "Chuột và bàn phím",
        panelCategoryFiles: "Tệp",
        windowMaximizeName: "Phóng to cửa sổ",
        windowMaximizeCaption: "Nút màu xanh lục phóng to cửa sổ mà không tạo thêm Không gian làm việc mới.",
        windowMaximizeActiveNow: "Đang bật ghi đè nút xanh lục",
        windowMaximizeNeedsAccessibility: "Cần quyền Trợ năng để hoạt động.",
        keyDebounceName: "Chống dội phím",
        keyDebounceEnable: "Lọc các phím bấm trùng lặp",
        keyDebounceCaption: "Lọc các lần nhấn phím trùng lặp quá nhanh.",
        keyDebounceActiveNow: "Bộ lọc đang hoạt động",
        keyDebounceGlobalWindow: "Khoảng thời gian chung",
        keyDebouncePerKeySection: "Phím cụ thể",
        keyDebouncePerKeyCaption: "Giá trị cho từng phím sẽ ghi đè khoảng thời gian chung. Dùng 0 ms để ngừng lọc phím đó.",
        keyDebounceKeyLabel: "Phím",
        keyDebounceWindowLabel: "Khoảng thời gian",
        keyDebounceAddKey: "Thêm phím",
        keyDebounceNoOverrides: "Chưa cấu hình phím cụ thể nào.",
        keyDebounceRemoveKey: "Xóa phím",
        cleaningPanelCaption: "Khóa bàn phím để bạn có thể vệ sinh an toàn.",
        cleaningOverlayTitle: "Bàn phím đã khóa để vệ sinh",
        cleaningOverlaySubtitle: "Nhấn Escape 5 lần để mở khóa",
        cleaningOverlayUnlock: "Mở khóa",
        cleaningOverlayMouseHint: "Chuột và bàn di chuột vẫn hoạt động bình thường",
        cleaningNeedsAxTitle: "Cần quyền Trợ năng",
        cleaningNeedsAxBody: "Để khóa bàn phím an toàn, Vorssaint cần quyền Trợ năng. Cấp quyền trong Cài đặt hệ thống và thử lại.",

        tabSupport: "Hỗ trợ",
        shortcutsPageCaption: "Chỉnh sửa mọi phím tắt toàn hệ thống của các tính năng đã cài đặt trên máy Mac này. Các phím tắt không hoạt động vẫn được lưu nhưng không chạy.",
        shortcutsPageTitle: "Phím tắt",
        settingsSearchPlaceholder: "Tìm kiếm cài đặt",
        donateHeading: "Giúp Vorssaint tiếp tục phát triển",
        donateMessage: "Vorssaint miễn phí, độc lập và được xây dựng trong thời gian rảnh của tôi. Nếu bạn muốn đóng góp tài chính, Buy Me a Coffee sẽ trực tiếp giúp tôi tiếp tục duy trì phát triển.",
        donateButton: "Ủng hộ trên Buy Me a Coffee",
        donateThanks: "Cảm ơn bạn đã đồng hành. 🖤",
        supportIntroTitle: "Giúp Vorssaint tiếp tục phát triển",
        supportIntroMessage: "Nếu bạn muốn ủng hộ tài chính cho quá trình phát triển, Buy Me a Coffee là nơi duy nhất để làm điều đó.",
        supportIntroStarButton: "Tặng sao Vorssaint trên GitHub",
        supportIntroStarMessage: "Sự ủng hộ tài chính không bao giờ là điều bắt buộc. Một ngôi sao trên GitHub giúp nhiều người biết đến Vorssaint hơn và tạo động lực thực sự cho dự án.",
        supportIntroCoffeeButton: "Ủng hộ trên Buy Me a Coffee",
        supportIntroLaterButton: "Để sau",
        supportIntroDoneButton: "Xong",
        discordIntroTitle: "Cộng đồng Discord Vorssaint vừa mới bắt đầu",
        discordIntroMessage: "Cộng đồng Vorssaint còn mới và đang được xây dựng. Hãy tham gia sớm để gặp gỡ những người dùng khác và cùng tạo dựng không gian thân thiện.",
        discordIntroBenefitHelp: "Nhận trợ giúp và chia sẻ quy trình làm việc",
        discordIntroBenefitFeedback: "Báo cáo lỗi, đề xuất cải tiến và định hình tính năng tiếp theo",
        discordIntroBenefitPreviews: "Xem các tính năng đang phát triển, bản xem trước sớm và tin tức phát hành",
        discordIntroJoinButton: "Tham gia cộng đồng Discord",
        communityIntroTitle: "Xem trước mọi người",
        communityIntroMessage: "Những ai theo dõi tôi trên X đã thấy nhiều thay đổi trong bản cập nhật này trước bất kỳ ai. Tôi đăng bản xem trước các tính năng sắp ra mắt và cách chúng hoạt động, để bạn nắm được những điều cơ bản trước khi bản cập nhật phát hành. Hãy theo dõi để đón chờ những điều tiếp theo!",
        communityIntroFollowButton: "Theo dõi @vorssaint trên X",
        homebrewOfficialIntroTitle: "Hiện đã có trong danh mục chính thức của Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint hiện có thể được cài đặt trực tiếp từ danh mục Homebrew chính thức.",
        homebrewOfficialIntroInstallLabel: "Cài đặt mới",
        homebrewOfficialIntroMigrationTitle: "Đã dùng tap cũ?",
        homebrewOfficialIntroMigrationMessage: "Chỉ cần xóa tap cũ một lần. Ứng dụng và cài đặt của bạn vẫn được giữ nguyên.",
        homebrewOfficialIntroCopyButton: "Sao chép lệnh",
        updateShowcaseTitle: "Có gì mới trong 3.1.4",
        updateShowcaseMessage: "Xem nhanh các cải tiến chính trong bản cập nhật này.",
        updateShowcaseUnavailable: "Video không thể tải vào lúc này. Bạn vẫn có thể tiếp tục.",
        updateShowcaseRestart: "Khởi động lại",
        showMenuBarIcon: "Hiện biểu tượng thanh menu",
        showMenuBarIconCaption: "Nếu biểu tượng của Vorssaint biến mất (macOS có thể ẩn biểu tượng khi thanh menu hết chỗ, thường gặp trên máy Mac có tai thỏ), hãy mở lại Vorssaint từ Ứng dụng hoặc Spotlight: thao tác đó sẽ tạo lại biểu tượng và mở cửa sổ này nếu nó vẫn bị ẩn. Nút phía trên cũng làm điều tương tự. Giữ ít biểu tượng trên thanh menu hơn sẽ giảm thiểu tối đa tình trạng này.",
        menuBarIconStillHiddenTitle: "Biểu tượng vẫn bị ẩn",
        menuBarIconStillHiddenBody: "Biểu tượng đã được tạo lại, nhưng macOS không có chỗ trống hiển thị. Thanh menu có thể đã hết chỗ: hãy bớt một số biểu tượng hoặc đóng bớt ứng dụng có menu dài rồi thử lại.",
        menuBarIconManagerHintFormat: "%@ đang mở và có thể đang giữ biểu tượng trong phần ẩn của nó. Hãy tìm Vorssaint ở đó hoặc đặt %@ luôn hiển thị Vorssaint.",
        shortcutRecording: "Nhấn phím tắt mới",
        shortcutReset: "Đặt lại",
        shortcutNone: "Không có",
        shortcutClear: "Xóa phím tắt",
        shortcutInvalid: "Dùng ít nhất Control, Option hoặc Command kết hợp với một phím.",
        shortcutPressKeys: "Nhấn các phím",
        shortcutEscapeHint: "Escape để hủy.",
        shortcutDeleteHint: "Delete để xóa.",
        shortcutNotCaptured: "Không ghi nhận được. macOS hoặc ứng dụng khác đã sử dụng tổ hợp này. Hãy thử tổ hợp khác.",
        shortcutConflictFormat: "Phím tắt này đã được sử dụng bởi %@.",
        shortcutUnavailable: "macOS đã từ chối phím tắt này. Hãy chọn phím tắt khác.",
        shelfShortcutToggle: "Phím tắt kệ tạm",
        switcherUsageHintFormat: "Giữ %@ để điều hướng; thả ra để kích hoạt cửa sổ. Shift hoặc ← để quay lại; W đóng cửa sổ; Q thoát ứng dụng; Esc để hủy.",
        musicBlockSection: "Phím phương tiện",
        musicBlockTitle: "Chặn Nhạc tự động mở",
        musicBlockCaption: "Ứng dụng Nhạc sẽ không còn tự mở khi bạn nhấn phím phương tiện. Bạn vẫn có thể tự mở ứng dụng.",
        musicBlockReplacementLabel: "Mở ứng dụng thay thế",
        musicBlockReplacementNone: "Không có",
        musicBlockChooseApp: "Chọn ứng dụng…",
        cleanerName: "Trình dọn dẹp",
        cleanerIntroTitle: "Dọn dẹp máy Mac của bạn",
        cleanerIntroCaption: "Quét tệp rác còn sót lại từ các ứng dụng đã gỡ, bộ nhớ đệm, nhật ký và Thùng rác. Bạn xem lại mọi thứ trước và các mục bị xóa sẽ vào Thùng rác.",
        cleanerScan: "Quét",
        cleanerScanning: "Đang quét…",
        cleanerCleaning: "Đang dọn dẹp…",
        cleanerCatLeftovers: "Tệp thừa từ ứng dụng đã gỡ",
        cleanerCatLoginItems: "Mục khởi động mồ côi",
        cleanerCatCaches: "Bộ nhớ đệm",
        cleanerCatLogs: "Nhật ký",
        cleanerCatDeveloper: "Rác phát triển phần mềm",
        cleanerCatTrash: "Thùng rác",
        cleanerLeftoversNote: "Được tìm thấy qua phân tích và chưa được chọn. Hãy kiểm tra đường dẫn trước khi đánh dấu.",
        cleanerLoginItemsNote: "Mục trong Mục khởi động sẽ biến mất sau khi khởi động lại máy Mac.",
        cleanerTrashNote: "Dọn sạch Thùng rác sẽ xóa vĩnh viễn.",
        cleanerCatDeviceBackups: "Bản sao lưu iPhone",
        cleanerDeviceBackupsCaption: "Các bản sao lưu iPhone và iPad cũ chiếm một phần lớn dung lượng mà macOS gọi là Khác. Chỉ xóa những bản bạn không còn cần; bản sao lưu mới sẽ được tạo khi bạn cắm lại thiết bị.",
        cleanerNothingFound: "Không có gì cần dọn dẹp. Máy Mac của bạn rất gọn gàng.",
        cleanerClean: "Dọn dẹp",
        cleanerDoneNote: "Các mục đã được chuyển vào Thùng rác và có thể khôi phục từ đó.",
        cleanerAgain: "Quét lại",
        cleanerRevealInFinder: "Hiện trong Finder",
        cleanerPanelCaption: "Tệp thừa từ ứng dụng, bộ nhớ đệm và nhật ký",
        cleanerSafeSection: "Dọn dẹp an toàn",
        cleanerOptionalSection: "Tùy chọn, xem lại trước",
        cleanerCatOtherCaches: "Bộ nhớ đệm khác",
        cleanerCachesCaption: "Tệp tạm thời mà ứng dụng sẽ tự tạo lại.",
        cleanerLogsCaption: "Nhật ký chẩn đoán cũ.",
        cleanerDeveloperCaption: "Tệp thừa từ bản dựng Xcode và trình giả lập.",
        cleanerLoginItemsCaption: "Mục khởi động còn lại của các ứng dụng không còn tồn tại.",
        cleanerLeftoversCaption: "Tệp còn sót lại từ các ứng dụng bạn đã gỡ cài đặt.",
        cleanerOtherCachesCaption: "An toàn để xóa, không ảnh hưởng đến hệ thống. Ứng dụng có thể mở chậm hơn một chút ở lần đầu và nội dung đã tải về như nhạc ngoại tuyến sẽ tải lại.",
        cleanerCleanSizeFormat: "Dọn dẹp %@",
        cleanerScheduleTitle: "Dọn dẹp tự động",
        cleanerScheduleOff: "Tắt",
        cleanerScheduleDaily: "Hàng ngày",
        cleanerScheduleWeekly: "Hàng tuần",
        cleanerScheduleCaption: "Chỉ tự động dọn dẹp phần an toàn vào thời gian đã chọn và chuyển mọi thứ vào Thùng rác.",
        cleanerScheduleLastFormat: "Lần dọn dẹp tự động gần nhất đã giải phóng %@.",
        cleanerAutoNotificationFormat: "Đã giải phóng %@ và chuyển vào Thùng rác.",
        cleanerScheduleNextFormat: "Lần dọn dẹp tiếp theo: %@.",
        cleanerScheduleRanFormat: "Lần dọn dẹp tự động gần nhất: %@.",
        cleanerScheduleNotifyToggle: "Thông báo khi hoàn tất",
        cleanerNotifDenied: "Thông báo Vorssaint đang bị tắt trong hệ thống.",
        cleanerNotifOpenSettings: "Mở Cài đặt thông báo…",
        launchAtLoginNeedsApplications: "Ứng dụng đang chạy từ vị trí không thể tự mở khi đăng nhập. Kéo Vorssaint vào thư mục Ứng dụng, mở từ đó và bật lại mục này.",
        launchAtLoginNeedsApproval: "Mục khởi động đã đăng ký nhưng đang bị tắt trong Cài đặt hệ thống. Mở Cài đặt hệ thống › Cài đặt chung › Mục khởi động & Tiện ích mở rộng và bật Vorssaint trong Mở khi đăng nhập.",
        ocrQRToggle: "Đọc mã QR",
        ocrQRCaption: "Nếu vùng chọn có mã QR, nội dung sẽ được hiển thị để sao chép hoặc mở.",
        ocrQRCopied: "Đã sao chép mã QR",
        qrResultTitle: "Mã QR",
        qrResultCopy: "Sao chép",
        qrResultOpen: "Mở liên kết",
        highlightsTitle: "Mới trong bản cập nhật này",
        highlightsTitleClipboardRedesign: "Bảng tạm được thiết kế lại",
        highlightsCaptionDockPreview: "Xem trước trên Dock hiện hoạt động khi bật tính năng phóng to Dock",
        highlightsCaptionScreenshot: "Công cụ chụp màn hình có thêm kính lúp điểm ảnh và đọc mã QR",
        highlightsCaptionSnippetLibrary: "Menu đoạn trích có thể tìm kiếm và gõ bất kỳ đoạn trích nào ngay tại con trỏ",
        highlightsCaptionCapturePalette: "Một phím tắt hiện mở bảng nổi cho ảnh chụp màn hình, quay video, văn bản màn hình và màu sắc với các nút điều khiển tiện lợi.",
        highlightsCaptionClipboardRedesign: "Lịch sử bảng tạm hiện mở dưới dạng bảng nhỏ gọn với các hàng thoáng đãng và bản xem trước theo yêu cầu để đọc hoặc chỉnh sửa mục đầy đủ.",
        highlightsConfigure: "Thiết lập",
        highlightsTry: "Dùng thử",
        highlightsSeeAll: "Xem tất cả thay đổi",
        switcherCurrentSpaceOnly: "Chỉ hiển thị màn hình hiện tại",
        switcherCurrentSpaceOnlyCaption: "Chỉ liệt kê các cửa sổ từ màn hình bạn đang ở. Việc chọn cửa sổ không bao giờ chuyển bạn sang màn hình khác.",
        shelfFileMissing: "Tệp không còn tồn tại",
        previewSizeSmall: "Nhỏ",
        mixerSoundEffectsOutputTitle: "Âm thanh hệ thống",
        mixerSoundEffectsOutputTooltip: "Chọn nơi phát âm thanh cảnh báo và hiệu ứng",
        monitorOpenActivityMonitor: "Mở Giám sát hoạt động",
        dockClickHide: "Nhấp vào biểu tượng Dock để ẩn ứng dụng",
        dockClickHideCaption: "Ứng dụng hiện tại sẽ ẩn khi bạn nhấp vào biểu tượng Dock của nó. Nhấp lại để hiển thị lại.",
        monitorMemoryMetricLabel: "Đo bộ nhớ theo",
        memoryMetricUsed: "Bộ nhớ đã dùng",
        memoryMetricApp: "Bộ nhớ ứng dụng",
        keepAwakeRightClickToggle: "Nhấp chuột phải vào biểu tượng thanh menu để bật/tắt Giữ thức",
        keepAwakeRightClickToggleCaption: "Thay thế menu ngữ cảnh nhấp chuột phải.",
        urlCleanerRulesTitle: "Quy tắc dọn dẹp",
        urlCleanerRulesCaption: "Trang web đính kèm các tham số này vào liên kết chia sẻ để theo dõi nguồn gốc liên kết. Khi bật, tham số sẽ bị xóa khi liên kết được dọn dẹp; khi tắt, nó được giữ lại. Các tên bạn thêm có thể xóa được.",
        urlCleanerRulesCoverageCaption: "Danh sách này bao gồm nhiều đường dẫn chia sẻ khác nhau của trang web — trang web, ứng dụng, phòng trực tiếp — đó là lý do danh sách dài; một liên kết thực tế thường chỉ mang 2 đến 4 tham số.",
        urlCleanerRulesAllSites: "Tất cả trang web",
        urlCleanerRulesCountSingular: "1 tham số",
        urlCleanerRulesCountPluralFormat: "%d tham số",
        urlCleanerRulesAddSite: "Thêm trang web",
        urlCleanerRulesParameterPlaceholder: "Tên tham số",
        urlCleanerRulesMatchCaption: "Viết tên bên trái dấu = , ví dụ: utm_source. Tên khớp sẽ xóa tham số đó khỏi liên kết và giữ nguyên phần còn lại.",
        urlCleanerRulesAddButton: "Thêm",
        urlCleanerRulesRemoveButton: "Xóa tên",
        urlCleanerRulesRemoveSiteButton: "Tắt tất cả quy tắc cho trang web này",
        urlCleanerRemovedFormat: "Đã xóa %@",
        switcherSearchPin: "Ghim tìm kiếm bằng phím S",
        switcherSearchPinCaption: "Phím S bắt đầu tìm kiếm và ghim mở trình chuyển đổi, giúp việc gõ không tạo ra ký tự đặc biệt khi phím tắt dùng ⌥, và tìm kiếm bắt đầu bằng Q hoặc W không vô tình đóng cửa sổ hoặc thoát ứng dụng.",
        invertVerticalScroll: "Đảo ngược cuộn dọc",
        invertHorizontalScroll: "Đảo ngược cuộn ngang",
        switcherShowShortcutHints: "Hiện gợi ý phím tắt",
        switcherShowShortcutHintsCaption: "Hiển thị phím tắt ứng dụng và cửa sổ bên dưới biểu tượng.",
        uninstallerHomebrewPackageFormat: "%@ cũng sẽ được gỡ khỏi Homebrew.",
        shelfEdgeToggle: "Mở gần cạnh màn hình",
        shelfEdgeCaption: "Kéo tệp về phía cạnh màn hình để hé mở kệ. Thả tệp vào đó hoặc kéo lùi lại để thu kệ về.",
        focusFollowsMouseName: "Tiêu điểm theo chuột",
        focusFollowsMouseCaption: "Tập trung và đưa cửa sổ dưới con trỏ lên trên sau một khoảng dừng ngắn.",
        focusFollowsMouseDelay: "Độ trễ di chuột",
        switcherMinimizedPlacementLabel: "Cửa sổ thu nhỏ",
        switcherMinimizedPlacementNormal: "Thứ tự bình thường",
        switcherMinimizedPlacementEnd: "Đặt ở cuối",
        switcherMinimizedPlacementHidden: "Ẩn",
        switcherShowFullscreenWindows: "Hiện cửa sổ toàn màn hình"
    )
}
